#!/usr/bin/env bash
# Idempotent Cloud Agent install for periscope.
# Dependency and toolchain setup only; no servers and no tests.
#
# Go must already be installed and available on PATH. This installer does not
# install or replace Go. Checkout paths come from this file's directory.
# Toolchain exports are written for later shells:
# ~/.config/periscope/cloud-agent-env.sh (sourced from ~/.bashrc, ~/.profile,
# and /etc/profile.d, and exported as BASH_ENV) and `go env -w` for CGO, which
# the go command reads with no shell startup files.
# PERISCOPE_CLOUD_PREFIX, when set, is the destination root instead of /.
set -euo pipefail

NODE_VERSION=24.21.0
# nodejs.org SHASUMS256.txt entry for node-v24.21.0-linux-x64.tar.xz.
NODE_TARBALL_SHA256=fd8e59d5a511510f6a298afb548f18c7d2b1be404d8b4a27d94fbe49f56cb2d6
NPM_VERSION=11.21.0
GCL_VERSION=v2.11.4
GCL_MODULE=github.com/golangci/golangci-lint/v2/cmd/golangci-lint

: "${HOME:?HOME is required}"

if ! command -v go >/dev/null 2>&1; then
  echo "Go is required on PATH. This installer does not install Go." >&2
  exit 1
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dest_root="${PERISCOPE_CLOUD_PREFIX:-}"
usr_local_bin="${dest_root}/usr/local/bin"
profile_d="${dest_root}/etc/profile.d"
env_file="${HOME}/.config/periscope/cloud-agent-env.sh"
sqlite_include="${repo_root}/.sqlite-include"

as_root() {
  if [ -n "${PERISCOPE_CLOUD_PREFIX:-}" ] || [ "$(id -u)" -eq 0 ]; then
    "$@"
  else
    sudo "$@"
  fi
}

link_toolchain_bins() {
  local cmd
  for cmd in node npm npx corepack golangci-lint; do
    if [ -e "${usr_local_bin}/${cmd}" ]; then
      ln -sfn "${usr_local_bin}/${cmd}" "${HOME}/.local/bin/${cmd}"
    fi
  done
}

write_shell_env() {
  local cgo_block=""
  if [ -f "${sqlite_include}/sqlite3.h" ]; then
    cgo_block="$(cat <<EOF
sqlite_include=$(printf '%q' "${sqlite_include}")
if [ -f "\${sqlite_include}/sqlite3.h" ]; then
  case "\${CGO_CFLAGS:-}" in
    *-I\${sqlite_include}*) ;;
    *) CGO_CFLAGS="-O2 -g -I\${sqlite_include}\${CGO_CFLAGS:+ \${CGO_CFLAGS}}" ;;
  esac
  export CGO_CFLAGS
fi
EOF
)"
  fi
  cat > "${env_file}" <<EOF
# Generated by the periscope cloud install. Re-run that script to refresh.
local_bin="\${HOME}/.local/bin"
case ":\${PATH:-}:" in
  *":\${local_bin}:"*) ;;
  *) PATH="\${local_bin}\${PATH:+:\${PATH}}" ;;
esac
export PATH
export BASH_ENV="\${HOME}/.config/periscope/cloud-agent-env.sh"
${cgo_block}
export CGO_ENABLED=1
EOF
  chmod 0644 "${env_file}"
}

install_profile_hook() {
  local source_line rc profile_body profile_tmp
  source_line=". $(printf '%q' "${env_file}")"
  for rc in "${HOME}/.bashrc" "${HOME}/.profile"; do
    if [ ! -f "${rc}" ] || ! grep -qxF "${source_line}" "${rc}"; then
      printf '\n%s\n' "${source_line}" >> "${rc}"
    fi
  done
  profile_body="${profile_d}/periscope-cloud.sh"
  profile_tmp="$(mktemp)"
  cat > "${profile_tmp}" <<'EOF'
# Periscope cloud toolchain. The user env file owns PATH and CGO exports.
if [ -n "${HOME:-}" ] && [ -f "${HOME}/.config/periscope/cloud-agent-env.sh" ]; then
  . "${HOME}/.config/periscope/cloud-agent-env.sh"
fi
EOF
  as_root cp "${profile_tmp}" "${profile_body}"
  as_root chmod 0644 "${profile_body}"
  rm -f "${profile_tmp}"
}

persist_toolchain() {
  write_shell_env
  install_profile_hook
  go env -w CGO_ENABLED=1
  if [ -f "${sqlite_include}/sqlite3.h" ]; then
    go env -w "CGO_CFLAGS=-O2 -g -I${sqlite_include}"
  else
    go env -u CGO_CFLAGS
  fi
}

export PATH="${HOME}/.local/bin${PATH:+:${PATH}}"
export CGO_ENABLED=1
export DEBIAN_FRONTEND=noninteractive

as_root apt-get update
as_root apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  curl \
  git \
  pkg-config \
  libsqlite3-dev \
  xz-utils

mkdir -p "${HOME}/go/pkg/mod" "${HOME}/.cache/go-build" "${HOME}/.local/bin" \
  "${HOME}/.config/periscope"
if [ ! -w "${HOME}/go" ] || [ ! -w "${HOME}/go/pkg/mod" ] || [ ! -w "${HOME}/.cache/go-build" ]; then
  as_root chown -R "$(id -u):$(id -g)" "${HOME}/go" "${HOME}/.cache/go-build"
fi

as_root mkdir -p "${usr_local_bin}" "${profile_d}"

if ! "${usr_local_bin}/node" -v 2>/dev/null | grep -qx "v${NODE_VERSION}"; then
  tmp="$(mktemp -d)"
  tarball="${tmp}/node.tar.xz"
  curl -fsSL \
    "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" \
    -o "${tarball}"
  if ! echo "${NODE_TARBALL_SHA256}  ${tarball}" | sha256sum -c -; then
    rm -rf "${tmp}"
    echo "node tarball checksum mismatch" >&2
    exit 1
  fi
  as_root tar -xJf "${tarball}" -C "${dest_root}/usr/local" \
    --strip-components=1 --no-same-owner
  rm -rf "${tmp}"
fi
link_toolchain_bins

if ! "${usr_local_bin}/npm" -v 2>/dev/null | grep -qx "${NPM_VERSION}"; then
  as_root env PATH="${usr_local_bin}:${PATH}" npm install -g "npm@${NPM_VERSION}"
  link_toolchain_bins
fi

if ! "${usr_local_bin}/golangci-lint" version 2>/dev/null | grep -Eq '2\.11\.4([^0-9]|$)'; then
  tmp="$(mktemp -d)"
  GOBIN="${tmp}" go install "${GCL_MODULE}@${GCL_VERSION}"
  as_root install -m 0755 "${tmp}/golangci-lint" "${usr_local_bin}/golangci-lint"
  rm -rf "${tmp}"
  link_toolchain_bins
fi

cd "${repo_root}"
go mod download
if [ -f Makefile ] && grep -q '^sqlite-vec-header:' Makefile; then
  make sqlite-vec-header
fi
if [ -f Makefile ] && grep -q '^pricing-snapshot:' Makefile; then
  make pricing-snapshot
fi

persist_toolchain

if [ -f frontend/package-lock.json ]; then
  (cd "${repo_root}/frontend" && npm ci)
fi
